server:
  port: 6620
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://192.168.42.119:3306/shop_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    druid:
      #连接池初始化大小
      initial-size: 5
      #最小空闲连接数
      min-idle: 10
      #最大连接数
      max-active: 200



#Redis配置

  redis:
    database: 0  #Redis索引0~15，默认为0
    host: 192.168.42.118
    port: 6379
    password:  #密码（默认为空）
#    lettuce: # 这里标明使用lettuce配置
#      pool:
#        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 5     #连接池中的最大空闲连接
#        min-idle: 0     #连接池中的最小空闲连接
    timeout: 10000ms    #连接超时时间（毫秒）
swagger:
  enabled: true
  ip: localhost